services:
  registry:
    image: registry:2.7
    environment:
      - REGISTRY_HTTP_SECRET=my_registry_secret
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - /opt/docker-registry:/var/lib/registry
      - ./registry-config/simple.yml:/etc/docker/registry/config.yml
    networks:
      - internal

  ui:
    image: joxit/docker-registry-ui:latest
    environment:
      - REGISTRY_TITLE=Private Registry
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SINGLE_REGISTRY=true
    depends_on:
      - registry
    networks:
      - web
      - internal
    labels:
      traefik.backend: 'registry.mydomain.com'
      traefik.frontend.rule: 'Host:registry.mydomain.com'
      traefik.enable: 'true'
      traefik.port: 80
      traefik.docker.network: 'traefik-net'
      traefik.frontend.auth.basic: 'admin:$apr1$XXrpwZre$ItZSXpoeB6bdPLCGT7eXG0'
      traefik.frontend.passHostHeader: 'true'

networks:
  internal:
  proxy:
    external: true
