services:
  registry-server:
    image: registry:2.8.3
    restart: always
    container_name: registry-server
    volumes:
      - registry_data:/var/lib/registry
      - ./config.yml:/etc/docker/registry/config.yml
      - ./htpasswd:/etc/docker/registry/htpasswd
    networks:
      - internal

  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    container_name: registry-ui
    depends_on:
      - registry-server
    networks:
      - web
      - internal
    # ports:
    #   - 80:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Registry
      - NGINX_PROXY_PASS_URL=http://registry-server:5000

      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    labels:
      traefik.enable: 'true'
      traefik.docker.network: 'web'
      traefik.backend: 'registry-wp.arsalanse.ir'
      traefik.frontend.rule: 'Host:registry-wp.arsalanse.ir'
      traefik.port: 80
      traefik.frontend.auth.basic: 'admin:$2y$05$dBabEFr78GgH93mGx1KMQucYhEC4iJle.GhDuRdvvwzhTyQmEfWUe'
      traefik.frontend.passHostHeader: 'true'

networks:
  internal:
  proxy:
    external: true

volumes:
  registry_data:
