- name: Services directory
  ansible.builtin.file:
    path: ~/s3
    state: directory
    mode: '700'

- name: Download mc
  ansible.builtin.get_url:
    url: https://dl.min.io/client/mc/release/linux-amd64/mc
    dest: ~/s3/mc
    mode: '0755'

# - name: Set minio alias
#   ansible.builtin.command: ~/s3/mc alias set {{ alias }} {{ s3_endpoint }} {{ access_key }} {{ secret_key }}
#   changed_when: true

- name: Install mysqldump
  ansible.builtin.apt:
    name:
      - mysql-client
    state: present
    update_cache: true
    allow_unauthenticated: true

- name: Script directory
  ansible.builtin.file:
    path: ~/scripts
    state: directory
    mode: '700'

- name: Backup script
  ansible.builtin.copy:
    src: files/db_backup.sh
    dest: ~/scripts/db_backup.sh
    owner: root
    group: root
    mode: '700'

- name: Add backup to crontab
  ansible.builtin.cron:
    name: mysql dump all databases
    minute: "01"
    hour: "3"
    user: root
    job: "~/scripts/db_backup.sh > /dev/null 2>&1"
