- name: Check whether "/swapfile1" exists
  ansible.builtin.stat:
    path: /swapfile1
  register: id_check_swap

- name: Print a debug message
  ansible.builtin.debug:
    msg: "Path exists and is a regular file"
  when: id_check_swap.stat.isreg is defined and id_check_swap.stat.isreg

# - name: Fail it if "/swapfile1" exists
#   ansible.builtin.fail:
#     msg: Swap file exists
#   when: id_check_swap.stat.exists

- name: Allocate the swap file
  ansible.builtin.command: fallocate -l {{ swap_vars.size }} /swapfile1
  changed_when: true
  when: id_check_swap.stat.isreg == false

- name: Change permission of the swap file
  ansible.builtin.file:
    path: /swapfile1
    mode: "600"
  when: id_check_swap.stat.isreg == false

- name: Create a swap area on the swap file
  ansible.builtin.command: mkswap /swapfile1
  changed_when: true
  when: id_check_swap.stat.isreg == false

- name: Activate the swap file as a swap memory
  ansible.builtin.command: swapon /swapfile1
  changed_when: true
  when: id_check_swap.stat.isreg == false

- name: Add to fstab
  ansible.builtin.lineinfile:
    dest: /etc/fstab
    regexp: "/swapfile1"
    line: "/swapfile1 none swap sw 0 0"
  when: id_check_swap.stat.isreg == false
