- name: Launch mysql database container
  community.docker.docker_container:
    name: mysql
    image: mysql:8.2.0
    recreate: true
    restart_policy: always
    pull: true
    volumes:
      - "{{ mysql_volume }}:/var/lib/mysql"
    networks:
      - name: "{{ mysql_network }}"
        aliases:
          - db
    published_ports:
      - "127.0.0.1:33306:3306"
    labels:
      traefik.enable: "false"
    env:
      TZ: "{{ mysql_timezone }}"
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      MYSQL_DATABASE: "{{ mysql_database }}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
