services:
  wordpress:
    image: docker.io/bitnami/wordpress:6.4.2
#    volumes:
#      - 'wordpress_data:/bitnami/wordpress'
    environment:
      - WORDPRESS_DATABASE_HOST=mysql
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_NAME=WPDatabase
      - WORDPRESS_DATABASE_USER=WPDBUser
      - WORDPRESS_DATABASE_PASSWORD=lovXV06xcL3VjzSDvJl0wRvz8Z9lyx0LtbuMjm6+JhE=
      - WORDPRESS_BLOG_NAME=stagingBlog
      - WORDPRESS_USERNAME=adminwp
      - WORDPRESS_PASSWORD=eg13TDRa1OsBCH2uqYkymxvsbCPtK4zLsGhH6J2HdDI=
      - WORDPRESS_SKIP_BOOTSTRAP=yes
      - WORDPRESS_ENABLE_REVERSE_PROXY=yes
    networks:
      - web
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.wpblog.entrypoints=web"
      - "traefik.http.routers.wpblog.rule=Host(`staging-wp.arsalanse.ir`)"
      - "traefik.http.routers.wpblog.tls=false"
      # - "traefik.http.routers.wpblog.tls.certresolver=letsencrypt"
      - "traefik.http.services.wpblog.loadbalancer.server.port=8080"

# volumes:
#   wordpress_data:

networks:
  web:
    external: true
  database:
    external: true
